services:
  culinary-vault-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    name: culinary-vault-network
